import { createHash, randomBytes } from "node:crypto";
import type { TabulaDb } from "@tabula/db";
import { sql } from "kysely";

/**
 * Short-lived auth challenges persisted in `core.auth_challenges` (migration 0013)
 * so they survive restarts and work across multiple API processes:
 *  - `mfa_login`  — password verified, waiting for the TOTP code
 *  - `mfa_enroll` — TOTP secret generated by /mfa/setup, waiting for /mfa/enable
 *  - `oauth_state` — Google OAuth `state` parameter
 */
export type ChallengeKind = "mfa_login" | "mfa_enroll" | "oauth_state";

export interface ChallengeRow {
  id: string;
  user_id: string | null;
  data: Record<string, unknown>;
  attempts: number;
}

function hashToken(token: string): Buffer {
  return createHash("sha256").update(token, "utf8").digest();
}

export async function createChallenge(
  db: TabulaDb,
  kind: ChallengeKind,
  opts: { userId?: string | null; data?: Record<string, unknown>; ttlMs: number; token?: string },
): Promise<string> {
  const token = opts.token ?? randomBytes(32).toString("base64url");
  // Opportunistic cleanup of expired rows.
  await sql`DELETE FROM core.auth_challenges WHERE expires_at < now() - interval '1 hour'`.execute(db);
  if (opts.userId && kind === "mfa_enroll") {
    // Only one pending enrollment per user.
    await sql`
      DELETE FROM core.auth_challenges WHERE user_id = ${opts.userId} AND kind = 'mfa_enroll'
    `.execute(db);
  }
  await sql`
    INSERT INTO core.auth_challenges (kind, token_hash, user_id, data, expires_at)
    VALUES (
      ${kind}, ${hashToken(token)}, ${opts.userId ?? null},
      ${JSON.stringify(opts.data ?? {})}::jsonb,
      ${new Date(Date.now() + opts.ttlMs)}
    )
  `.execute(db);
  return token;
}

/** Look up a live (unexpired, unconsumed) challenge by token. */
export async function findChallenge(
  db: TabulaDb,
  kind: ChallengeKind,
  token: string,
): Promise<ChallengeRow | null> {
  const res = await sql<ChallengeRow>`
    SELECT id, user_id, data, attempts
    FROM core.auth_challenges
    WHERE kind = ${kind} AND token_hash = ${hashToken(token)}
      AND consumed_at IS NULL AND expires_at > now()
    LIMIT 1
  `.execute(db);
  return res.rows[0] ?? null;
}

/** Latest live challenge of a kind for a user (used for mfa_enroll). */
export async function findUserChallenge(
  db: TabulaDb,
  kind: ChallengeKind,
  userId: string,
): Promise<ChallengeRow | null> {
  const res = await sql<ChallengeRow>`
    SELECT id, user_id, data, attempts
    FROM core.auth_challenges
    WHERE kind = ${kind} AND user_id = ${userId}
      AND consumed_at IS NULL AND expires_at > now()
    ORDER BY created_at DESC
    LIMIT 1
  `.execute(db);
  return res.rows[0] ?? null;
}

/** Atomically consume a challenge; false when someone else already consumed it. */
export async function consumeChallenge(db: TabulaDb, id: string): Promise<boolean> {
  const res = await sql`
    UPDATE core.auth_challenges SET consumed_at = now()
    WHERE id = ${id} AND consumed_at IS NULL
  `.execute(db);
  return Number(res.numAffectedRows ?? 0n) > 0;
}

/** Record a failed attempt; returns the new attempt count. */
export async function bumpChallengeAttempts(db: TabulaDb, id: string): Promise<number> {
  const res = await sql<{ attempts: number }>`
    UPDATE core.auth_challenges SET attempts = attempts + 1
    WHERE id = ${id}
    RETURNING attempts
  `.execute(db);
  return res.rows[0]?.attempts ?? 0;
}
